chore: use Linux container CPU quota
NVIDIA/dcgm-exporter pull request #266
Opened 2024-02-26 01:18 UTC by uhthomas

Go is not cgroup aware and by default will set GOMAXPROCS to the number of available threads, regardless of whether it is within the allocated quota. This behaviour causes high amount of CPU throttling and degraded application performance.

Fixes: #265

2024-03-01 18:07 UTC, glowkey submitted a review, later dismissed
LGTM

2024-03-01 20:36 UTC, nvvfedorov requested changes
@uhthomas, Please resolve conflicts and sign off your PR: https://github.com/NVIDIA/dcgm-exporter/blob/main/CONTRIBUTING.md

2024-03-18 15:33 UTC, glowkey approved these changes
LGTM

2024-03-18 15:34 UTC, nvvfedorov approved these changes
LGTM

2024-03-18 15:34 UTC, merged